import Foundation

/// Canonical tool names shared by the router, the tools and the tests.
public enum ToolName {
    public static let remindersList = "reminders_list"
    public static let remindersCreate = "reminders_create"
    public static let remindersComplete = "reminders_complete"
    public static let remindersSearch = "reminders_search"
    public static let musicPlay = "music_play"
    public static let musicControl = "music_control"
    public static let musicNowPlaying = "music_now_playing"
    public static let musicVolume = "music_volume"
    public static let openApp = "open_app"
    public static let closeApp = "close_app"
    public static let openURL = "open_url"
    public static let openFile = "open_file"
    public static let revealInFinder = "reveal_in_finder"
    public static let openSettings = "open_settings"
    public static let startCodingSession = "start_coding_session"
    public static let moveToTrash = "move_to_trash"
    public static let runCommand = "run_command"
    public static let browserSearch = "browser_search"
    public static let webSearch = "web_search"
    public static let timerSet = "timer_set"
    public static let timerList = "timer_list"
    public static let timerCancel = "timer_cancel"
    public static let weather = "weather"
    public static let calendarEvents = "calendar_events"
    public static let systemVolume = "system_volume"
    public static let darkMode = "dark_mode"
    public static let systemInfo = "system_info"
    public static let calculate = "calculate"
    public static let fileSearch = "file_search"
    public static let clipboard = "clipboard"
    public static let dictionary = "dictionary"
    public static let mailSearch = "mail_search"
    public static let calendarUpdate = "calendar_update"
    public static let undoLastAction = "undo_last_action"
    public static let calendarCreate = "calendar_create"
    public static let shortcutRun = "shortcut_run"
    public static let focus = "focus"
    public static let energyStatus = "energy_status"
    public static let lowPowerMode = "low_power_mode"
}
